/**
* This file was automatically generated by @cosmwasm/ts-codegen@1.11.1.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import * as _0 from "./InjectiveInterchainPersona.types";
import * as _1 from "./InjectiveInterchainPersona.client";
import * as _2 from "./InjectiveInterchainPersona.message-composer";
export namespace contracts {
  export const InjectiveInterchainPersona = {
    ..._0,
    ..._1,
    ..._2
  };
}