/**
* This file was automatically generated by @cosmwasm/ts-codegen@1.11.1.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

export interface InstantiateMsg {}
export type ExecuteMsg = {
  add_wallet: {
    wallet: Wallet;
  };
} | {
  remove_wallet: {
    wallet: Wallet;
  };
};
export type Chain = "injective" | "multivers_x";
export interface Wallet {
  address: string;
  chain: Chain;
}
export type QueryMsg = {
  get_persona: {
    address: Addr;
  };
} | {
  get_persona_from_linked_wallet: {
    wallet: Wallet;
  };
};
export type Addr = string;
export interface Persona {
  linked_wallets: Wallet[];
}
export type ArrayOfAddr = Addr[];