/**
* This file was automatically generated by @cosmwasm/ts-codegen@1.11.1.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import { Coin } from "@cosmjs/amino";
import { MsgExecuteContractEncodeObject } from "@cosmjs/cosmwasm-stargate";
import { MsgExecuteContract } from "cosmjs-types/cosmwasm/wasm/v1/tx";
import { toUtf8 } from "@cosmjs/encoding";
import { InstantiateMsg, ExecuteMsg, Chain, Wallet, QueryMsg } from "./InjectiveInterchainPersona.types";
export interface InjectiveInterchainPersonaMsg {
  contractAddress: string;
  sender: string;
  addWallet: ({
    wallet
  }: {
    wallet: Wallet;
  }, _funds?: Coin[]) => MsgExecuteContractEncodeObject;
  removeWallet: ({
    wallet
  }: {
    wallet: Wallet;
  }, _funds?: Coin[]) => MsgExecuteContractEncodeObject;
}
export class InjectiveInterchainPersonaMsgComposer implements InjectiveInterchainPersonaMsg {
  sender: string;
  contractAddress: string;
  constructor(sender: string, contractAddress: string) {
    this.sender = sender;
    this.contractAddress = contractAddress;
    this.addWallet = this.addWallet.bind(this);
    this.removeWallet = this.removeWallet.bind(this);
  }
  addWallet = ({
    wallet
  }: {
    wallet: Wallet;
  }, _funds?: Coin[]): MsgExecuteContractEncodeObject => {
    return {
      typeUrl: "/cosmwasm.wasm.v1.MsgExecuteContract",
      value: MsgExecuteContract.fromPartial({
        sender: this.sender,
        contract: this.contractAddress,
        msg: toUtf8(JSON.stringify({
          add_wallet: {
            wallet
          }
        })),
        funds: _funds
      })
    };
  };
  removeWallet = ({
    wallet
  }: {
    wallet: Wallet;
  }, _funds?: Coin[]): MsgExecuteContractEncodeObject => {
    return {
      typeUrl: "/cosmwasm.wasm.v1.MsgExecuteContract",
      value: MsgExecuteContract.fromPartial({
        sender: this.sender,
        contract: this.contractAddress,
        msg: toUtf8(JSON.stringify({
          remove_wallet: {
            wallet
          }
        })),
        funds: _funds
      })
    };
  };
}